// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_bubble_power = "CgkIlcHm8P0FEAIQEA"; // <GPGSID>
        public const string achievement_coin_collector_2_middle_class = "CgkIlcHm8P0FEAIQFQ"; // <GPGSID>
        public const string achievement_sharing_is_caring = "CgkIlcHm8P0FEAIQDA"; // <GPGSID>
        public const string leaderboard_longest_escape = "CgkIlcHm8P0FEAIQBA"; // <GPGSID>
        public const string achievement_buy_the_eagle = "CgkIlcHm8P0FEAIQCg"; // <GPGSID>
        public const string achievement_coins_in_one_run_1 = "CgkIlcHm8P0FEAIQGQ"; // <GPGSID>
        public const string achievement_level_up_1_reach_level_15 = "CgkIlcHm8P0FEAIQCQ"; // <GPGSID>
        public const string achievement_small_power = "CgkIlcHm8P0FEAIQDw"; // <GPGSID>
        public const string achievement_coin_collector_3_elite_class = "CgkIlcHm8P0FEAIQFg"; // <GPGSID>
        public const string leaderboard_total_escape_distance = "CgkIlcHm8P0FEAIQBg"; // <GPGSID>
        public const string achievement_level_up_3_reach_level_40__champion_levels = "CgkIlcHm8P0FEAIQGA"; // <GPGSID>
        public const string achievement_escape_distance_2_moderate_learner = "CgkIlcHm8P0FEAIQEw"; // <GPGSID>
        public const string achievement_level_up_2_reach_level_30 = "CgkIlcHm8P0FEAIQFw"; // <GPGSID>
        public const string achievement_rocket_power = "CgkIlcHm8P0FEAIQEg"; // <GPGSID>
        public const string achievement_big_power = "CgkIlcHm8P0FEAIQDg"; // <GPGSID>
        public const string achievement_first_time_dead_rip = "CgkIlcHm8P0FEAIQDQ"; // <GPGSID>
        public const string achievement_coin_collector_1_lower_class = "CgkIlcHm8P0FEAIQCA"; // <GPGSID>
        public const string achievement_buy_the_pidgeotto = "CgkIlcHm8P0FEAIQCw"; // <GPGSID>
        public const string achievement_escape_distance_3_master_escapist = "CgkIlcHm8P0FEAIQFA"; // <GPGSID>
        public const string achievement_escape_distance_1_starting_to_learn = "CgkIlcHm8P0FEAIQBw"; // <GPGSID>
        public const string achievement_coins_in_one_run_2 = "CgkIlcHm8P0FEAIQGg"; // <GPGSID>
        public const string achievement_speed_power = "CgkIlcHm8P0FEAIQEQ"; // <GPGSID>

}

